export const actions = {
    blogs: {
        BLOGS_DATA_FETCHING: "BLOGS_DATA_FETCHING",
        BLOGS_DATA_FETCHED: "BLOGS_DATA_FETCHED",
        BLOGS_DATA_ERROR: "BLOGS_DATA_ERROR",
        BLOGS_DATA_EDIT: "BLOGS_DATA_EDIT",
        BLOGS_DATA_DELETE: "BLOGS_DATA_DELETE",
        BLOGS_PAGE: "BLOGS_PAGE",
        BLOGS_HASMORE: "BLOGS_HASMORE",
        BLOGS_ALL_VISIBALE: "BLOGS_ALL_VISIBALE",
        BLOG_LIKE: "BLOG_LIKE",
        BLOG_COMMENT: "BLOG_COMMENT",
        BLOG_HEART: "BLOG_HEART"
    },
    popularBlogs: {
        POPULAR_DATA_FETCHING: "POUPLAR_DATA_FETCHING",
        POPULAR_DATA_FETCHED: "POPULAR_DATA_FETCHED",
        POPULAR_DATA_ERROR: "POPULAR_DATA_ERROR",
        POPULAR_DATA_DELETE: "POPULAR_DATA_DELETE"
    },
    favouriteBlos: {
        FAVOURITE_DATA_FETCHING: "FAVOURITE_DATA_FETCHING",
        FAVOURITE_DATA_FETCHED: "FAVOURITE_DATA_FETCHED",
        FAVOURITE_DATA_DELETE: "FAVOURITE_DATA_DELETE",
        FAVOURITE_DATA_ERROR: "FAVORITE_DATA_ERROR"
    },
    profile: {
        PROFILE_DATA_FETCHING: "PROFILE_DATA_FETCHING",
        PROFILE_DATA_FETCHED: "PROFILE_DATA_FETCHED",
        PROFILE_IMGAGE_UPDATE: "PROFILE_IMAGE_UPDATE",
        PROFILE_BIO_UPDATE: "PROFILE_BIO_UPDATE",
        PROFILE_BLOG_DELETE: "PROFILE_BLOG_DELETE",
        PROFILE_DATA_ERROR: "PROFILE_DATA_ERROR",
        PROFILE_INFINITY_SCROLL_LOADING: "PROFILE_INFINITY_SCROLL_LOADING",
        PROFILE_BLOG_ALL_VISIBLE: "PROFILE_BLOG_ALL_VISIBLE"
    }
}