export const actions = {
    blogs: {
        BLOGS_DATA_FETCHING: "BLOGS_DATA_FETCHING",
        BLOGS_DATA_FETCHED: "BLOGS_DATA_FETCHED",
        BLOGS_DATA_ERROR: "BLOGS_DATA_ERROR",
        BLOGS_DATA_EDIT: "BLOGS_DATA_EDIT",
        BLOGS_DATA_DELETE: "BLOGS_DATA_DELETE",
        BLOGS_PAGE: "BLOGS_PAGE",
        BLOGS_HASMORE: "BLOGS_HASMORE",
        BLOGS_ALL_VISIBALE: "BLOGS_ALL_VISIBALE"
    },
    popularBlogs: {
        POPULAR_DATA_FETCHING: "POUPLAR_DATA_FETCHING",
        POPULAR_DATA_FETCHED: "POPULAR_DATA_FETCHED",
        POPULAR_DATA_ERROR: "POPULAR_DATA_ERROR",
        POPULAR_DATA_DELETE: "POPULAR_DATA_DELETE"
    },
    favouriteBlos: {
        FAVOURITE_DATA_FETCHING: "FAVOURITE_DATA_FETCHING",
        FAVOURITE_DATA_FETCHED: "FAVOURITE_DATA_FETCHED",
        FAVOURITE_DATA_DELETE: "FAVOURITE_DATA_DELETE",
        FAVOURITE_DATA_ERROR: "FAVORITE_DATA_ERROR"
    }
}